### ISSUE TITLE
Release TODO list

### ISSUE THREAD

**Issue by Deamon5550** [TVPT/VoxelGunsmith#5]
<h3>Gunsmith</h3>
- [x] Log4jLogging (#4)
- [ ] Unit tests
- [x] text formatting support
- [x] event bus
- [x] undo/redo refactor
- [ ] Brush file format
- [x] Offline undo queues
    - [x] Undo other (/uu)
- [x] Expansion system support
- [x] Default aliases
- [x] vs range
- [ ] no-phys
- [ ] material lists (/vi)
    - [ ] Update brushes to support material lists
- [ ] Schematic saving/loading
- [ ] schematic lists
- [x] getblock abort for unloaded chunks
- [x] Debug issue with `/b ball material material`
- [x] Debug brush arg aliases (@Deamon5550)
- [ ] Block state support
- [x] persistence
- [ ] move more values to configuration
- [ ] debug log
- [x] warning of potential brush selection error (eg. `/b ball` with no action)
- [x] shape expansion (@Deamon5550)
- [ ] hyper-change
- [ ] per-player variable data storage
- [ ] Clear undo history command

<h3>Bukkit</h3>
- [ ] hyper-change
- [x] entities
- [ ] world wrap

<h3>Forge</h3>
- [ ] logging cleanup
- [ ] hyper-change
- [x] entities
- [x] biomes
- [x] scheduler
- [x] update for latest gunsmith changes
- [x] text colour

<h3>Sponge</h3>
- [x] chunks
- [x] permissions proxy
- [x] event proxy
- [ ] hyper-change
- [x] entities
- [x] biomes
- [x] update for gunsmith
- [x] gradle setup

<h3>VisualScripting</h3>
- [x] Unit tests
- [x] gradle setup

<h3>Standalone</h3>
- [x] basic renderer setup
- [x] gradle setup
- [ ] gunsmith basic impl
- [ ] chunks
- [ ] world
- [ ] chunk renderer
- [ ] lighting
- [ ] Gui setup
